### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by LaviLaza** [RaniSharim/ml_ex#1]
Hi Rani,
I reviewed the process and it overall it looks good. I have couple of questions regarding the cleansing process - see below - I haven't pushed any modification because I wanted to get your feedback first.
- Why drop avg_size_per_room and Avg_monthly_expense_on_pets_or_plants?

- How did you determine distribution dependency (line 32)

- We need to have raw data as well.. Need to split the data up front.

- Why did you decide to to treat income and garden size by ratio filling? There are other fields that could be treated similarly - like age and kids born in the last 10 years. Any specific reason?

I also included here a python notebook with my review (might help with the report) - see attached.

I'll move on to the feature selection and update you.

Thanks. 

[Data_cleansing_notebook.zip](https://github.com/RaniSharim/ml_ex/files/1502746/Data_cleansing_notebook.zip)

**Comment by RaniSharim** [comment]
1 + 4. They have 0.97~ correlation with other fields. The ratio.is practically linear. Couldnt find other fields like that. Its in the explaining text.

2. Saw the distribution per vote type for category features, or differance in mean, media and var per vote type in numerical ones. Its in the text as well.

3. Excersize text says otherwise. Splitting beforehand is in the extra assignments.

**Comment by LaviLaza** [comment]
Thanks for the updates.

1,4 - Cool. Do you have any numbers or graphs to support that? You'll probably need more than just the documentation in the code...

2 - Again do you have numbers or graphs to support that?

3 - The exercise notes are: "at the end of this task yo should have 3X2 data sets."
 If you choose to split it at the end you won't be able to get **raw data** because all of it is analyzed... 



![capture](https://user-images.githubusercontent.com/10574002/33228828-563149f2-d1cc-11e7-9a73-03a318fe1802.PNG)
![capture1](https://user-images.githubusercontent.com/10574002/33228830-564f3f0c-d1cc-11e7-88cb-c5af7a6d6b1b.PNG)

**Comment by RaniSharim** [comment]
1,4 -It's just running pairwise correlation on attributes and getting a number, I wrote which attributes I've tested and the significant numbers. I dont think there's a point to show 20 pairs with 0.2 - 0.5 correlation.

2. I have some examples in the file of table of cases where I see and don't see significance to the class. Again, I dont know if there's a point to show all the tables to all the 30+ attributes. The process is the same and pretty simple.

3. Ok, I'll make the changes.

**Comment by LaviLaza** [comment]
OK. Thanks.

**Comment by LaviLaza** [comment]
Feature selection notes:

- Consider changing 'maybe' (vote for large party) to 0.1 or some other non-zero value as it might produce unexpected results - I get warning when running the algos on it.

- Any specific reason you went with 60th percentile? I got good results with 45 - see notebook - But it does not really matter..

- I noticed that you use selector for backward elimination that you created for the filter methods - I guess this is not intentional..

The features I got (You can a look at the notebook to see the results:
Feature index: 0   Feature name: Occupation_Satisfaction
Feature index: 1   Feature name: Avg_monthly_expense_when_under_age_21
Feature index: 2   Feature name: AVG_lottary_expanses
Feature index: 3   Feature name: Avg_Satisfaction_with_previous_vote
Feature index: 4   Feature name: Garden_sqr_meter_per_person_in_residancy_area
Feature index: 5   Feature name: Financial_balance_score_(0-1)
Feature index: 8   Feature name: Avg_education_importance
Feature index: 13   Feature name: Yearly_IncomeK
Feature index: 14   Feature name: Avg_monthly_household_cost
Feature index: 15   Feature name: Phone_minutes_10_years
Feature index: 16   Feature name: Weighted_education_rank
Feature index: 18   Feature name: Avg_monthly_income_all_years
Feature index: 19   Feature name: Last_school_grades
Feature index: 21   Feature name: Political_interest_Total_Score
Feature index: 22   Feature name: Number_of_valued_Kneset_members
Feature index: 23   Feature name: Overall_happiness_score
Feature index: 25   Feature name: Will_vote_only_large_party_int
Feature index: 27   Feature name: Looking_at_poles_results_int
Feature index: 28   Feature name: Married_int
Feature index: 30   Feature name: Most_Important_Issue_0
Feature index: 31   Feature name: Most_Important_Issue_1
Feature index: 32   Feature name: Most_Important_Issue_2
Feature index: 33   Feature name: Most_Important_Issue_3
Feature index: 34   Feature name: Most_Important_Issue_4
Feature index: 35   Feature name: Most_Important_Issue_5
Feature index: 36   Feature name: Most_Important_Issue_6
Feature index: 37   Feature name: Most_Important_Issue_7

[PycharmProjects.zip](https://github.com/RaniSharim/ml_ex/files/1503331/PycharmProjects.zip)

**Comment by RaniSharim** [comment]
1. Maybe as 0 is what he showed in class. Basically a 'dont care'.

2. No specific reason, just that he said we need about half and i wanted to be conservative.

3. Yeah, thats a mistake.

**Comment by LaviLaza** [comment]
Regrading to '1', It seems that having 0 might produce anomalies when running analysis on it - the warning is about a possible division by zero - I haven't had the chance to look into it yet, but it might be worth a short investigation. 

Let me know if i can help with anything.

**Comment by RaniSharim** [comment]
Ok, I fixed the support for backward propegation.

Splitting to files will take a bit more time though, i need some free time for it.

**Comment by LaviLaza** [comment]
K.

Now we have the report and the bonus questions.
Are interested in doing those?

**Comment by LaviLaza** [comment]
Hi Rani,

Do you have any good way to visualise correlation between two features. I suspect we can reduce the numbers of features.

**Comment by RaniSharim** [comment]
You can do corralation with pandas with dataframe.corr(), close to 1 or -1 is linear correlation.

There is also mutual information, that he said yesterday that are some features that have it and non-linear relation, but I couldn't get it work, I almost always get the same result no matter what.

You can also do a scatterplot between two features, to see if you see any familiar function
