### ISSUE TITLE
Major changes

### ISSUE THREAD

**Issue by RaniSharim** [RaniSharim/ml_ex#2]
Hey, I've talked to the professor yesterday, and so made some changes:

1. I shuffly and split the data before starting to work on it, and output the raw files.

2. We're not supposed to drop lines with outlier detection, just to drop values. So I switched the k-nearest to just checking each value if it is more then 3 std from the mean and if so dropping it.

3. He said we should do the categorical feature split to true/false only after selecting it, so we wont select only part of it. So I moved it after the feature selection.

**Comment by LaviLaza** [comment]
Ok. I'll have a look tonight.
