### ISSUE TITLE
Ex3

### ISSUE THREAD

**Issue by RaniSharim** [RaniSharim/ml_ex#5]
Hey, I have a few questions:

1. You write on k-nearest neightbores 
"Plotting to see what should be the optimal k for the data (based results seems to be at k = 2)"
But on line 104 you seem to start from 3?

2. What is the reason for using differant cross validation values for each model?

3. Line 126, you don't seem to be setting the splitter parameter to the "best" value (ie 5) but just leaving as it was in the end of the loop (Line 84)?

**Comment by LaviLaza** [comment]
Here are my answers:
1. I actually noticed that in most cases I got the highest score around 5 neighbors (you can see it in the attached note book). But in any case, I thought that 2 neighbors will over-fit the data and so I didn't want to go with 2. I'll emphasize this point in the doc so it will be clear.

2.  If you refer to the cv (number of splits of the data), I just played around with those values to see if I notice any significant changes. I didn't, so I just left it with the last numbers I had... 
Anyways I changed the cv for Naive Bayes and DT to 20, to match the others..
In my examination of models (the 2nd stage) I used higher cv just to be more precise..As before, it does not really matter.

3. Good catch.. I missed that.. It does not change the final outcome which is still a bit higher for OvO (I get 95 for OvO and still 94.5 for DT). Let me know if you get different results.
