### ISSUE TITLE
Ex3 bonus

### ISSUE THREAD

**Issue by RaniSharim** [RaniSharim/ml_ex#6]
Hey, I've started with the bonus questions to ex3.
So far I did c, also plan on doing a.

Do you have a direction for b though? I'm not sure how to test which model is best for what.

**Comment by LaviLaza** [comment]
I'll have a look tonight.

**Comment by LaviLaza** [comment]
Actually I'm not sure what he means by different tasks. It seems to me that the better we predict each vote,  the better we predict the general distribution. I would send him an email ask for clarification.

**Comment by RaniSharim** [comment]
I've added the part 1.

He said to consider effect of size and false positives vs false negatives. 
But I don't think I'll have time for it anyway... Sorry.

**Comment by LaviLaza** [comment]
Alright then. I'll submit during the weekend.
